Repository raagakrishna/dots_and_boxes, pull requests merged in 2023-06, with the labels that each got.

#2 Backend Skeleton
  .gitignore
  api/swagger.yaml
  resource_server/pom.xml
  resource_server/src/main/java/za/resources/App.java
  resource_server/src/main/java/za/resources/models/JWTResponse.java
  resource_server/src/main/java/za/resources/models/User.java
  resource_server/src/main/java/za/resources/util/jwt/Algo.java
  resource_server/src/main/java/za/resources/util/jwt/Generator.java
  resource_server/src/main/java/za/resources/util/jwt/Provider.java
  resource_server/src/main/java/za/resources/util/jwt/Verifier.java
  resource_server/src/test/java/za/resources/AppTest.java
  server/pom.xml
  server/src/main/java/za/dots/App.java
  server/src/main/java/za/dots/controllers/PlayerCrudHandler.java
  server/src/main/java/za/dots/controllers/PlayersCrudHandler.java
  server/src/main/java/za/dots/controllers/RoomCrudHandler.java
  server/src/main/java/za/dots/controllers/interfaces/PlayerApi.java
  server/src/main/java/za/dots/controllers/interfaces/PlayersApi.java
  server/src/main/java/za/dots/controllers/interfaces/RoomApi.java
  server/src/main/java/za/dots/models/Dot.java
  server/src/main/java/za/dots/models/Game.java
  server/src/main/java/za/dots/models/Player.java
  server/src/main/java/za/dots/models/Room.java
  server/src/main/java/za/dots/models/Score.java
  server/src/test/java/za/dots/AppTest.java
Labels: enhancement, help wanted

#12 Feature/api
  api/swagger.yaml
Labels: documentation, enhancement

#41 Initial page created and made responsive.
  site/css/common.css
  site/css/footer.css
  site/css/header.css
  site/css/main.css
  site/css/tabs.css
  site/index.html
  site/js/common.js
  site/js/main.js
Labels: Frontend

#48 Create tables sql script.
  server/create_tables_scripts.sql
Labels: enhancement, Game logic

#51 Tested all endpoints.
  api/swagger.yaml
  server/src/main/java/za/dots/controllers/PlayerCrudHandler.java
  server/src/main/java/za/dots/controllers/PlayersCrudHandler.java
  server/src/main/java/za/dots/controllers/RoomCrudHandler.java
  server/src/main/java/za/dots/models/Game.java
  server/src/main/java/za/dots/models/Player.java
Labels: documentation, enhancement, Game logic

#58 Feature/frontend
  site/css/common.css
  site/css/game.css
  site/css/login_register.css
  site/css/main.css
  site/game.html
  site/index.html
  site/js/common.js
  site/js/game.js
  site/js/index.js
  site/js/login_register.js
  site/login.html
  site/register.html
Labels: Frontend

#56 Feature/backend endpoints
  api/swagger.yaml
  server/src/main/java/za/dots/App.java
  server/src/main/java/za/dots/controllers/RoomCrudHandler.java
  server/src/main/java/za/dots/controllers/interfaces/RoomApi.java
  server/src/main/java/za/dots/models/Game.java
  server/src/main/java/za/dots/models/PlayerLine.java
Labels: enhancement, Game logic

#72 All endpoints work from frontend
  api/swagger.yaml
  server/src/main/java/za/dots/App.java
  server/src/main/java/za/dots/controllers/RoomCrudHandler.java
  server/src/main/java/za/dots/controllers/interfaces/RoomApi.java
  site/css/common.css
  site/css/login_register.css
  site/js/common.js
  site/js/game.js
  site/js/index.js
  site/js/login_register.js
Labels: Game logic, Frontend

#75 create room endpoint works
  server/create_tables_scripts.sql
  server/src/main/java/za/dots/App.java
  server/src/main/java/za/dots/common/SharedFunctions.java
  server/src/main/java/za/dots/controllers/RoomCrudHandler.java
  server/src/main/java/za/dots/controllers/interfaces/RoomApi.java
  server/src/main/java/za/dots/db/DatasourceConnection.java
  server/src/main/java/za/dots/db/GameDao.java
  server/src/main/java/za/dots/db/RoomDao.java
Labels: Game logic

#77 Add try-catch. added findRoomByUsername.
  server/src/main/java/za/dots/App.java
  server/src/main/java/za/dots/controllers/PlayerCrudHandler.java
  server/src/main/java/za/dots/controllers/RoomCrudHandler.java
  server/src/main/java/za/dots/db/RoomDao.java
Labels: critical
